---
# nfs_client_using_kerberos/tasks/Debian_configure_nfs-common.yml

- name: 'Enable idmapd in /etc/default/nfs-common (needed for kerberized NFSv4)'
  lineinfile:
    path: '/etc/default/nfs-common'
    regex: '^NEED_IDMAPD'
    line: 'NEED_IDMAPD=yes'
    owner: 'root'
    group: 'root'
    mode: '0644'
  notify:
    - 'Debian: restart the rpc-gssd service'

- name: 'Enable gssd in /etc/default/nfs-common (needed for kerberized NFSv4)'
  lineinfile:
    path: '/etc/default/nfs-common'
    regex: '^NEED_GSSD'
    line: 'NEED_GSSD=yes'
    owner: 'root'
    group: 'root'
    mode: '0644'
  notify:
    - 'Debian: restart the rpc-gssd service'

- name: 'Start and enable the rpc-gssd service'
  service:
    name: 'rpc-gssd.service'
    state: 'started'
    enabled: 'true'
