---
# nfs_client_using_kerberos/tasks/main.yml

- name: 'Run tasks from Debian_configure_nfs-common.yml'
  ansible.builtin.include_tasks:
    file: Debian_configure_nfs-common.yml
  when:
    - 'ansible_os_family == "Debian"'
